version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/go/src/app
    tty: true

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=reco_dev
      - MYSQL_ROOT_PASSWORD=5w1h3581
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --innodb_file_per_table
      --innodb_file_format=BARRACUDA
      --innodb_large_prefix=1
    ports:
      - 3306:3306
